version: '3.9'
services:
  postgres:
    image: postgres:alpine
    container_name: org.servlets.project.rest
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: org.servlets.project.rest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123