create table File
(
    id     int primary key generated by default as identity,
    file_path varchar(255)

);
create table Users
(
    id     int primary key generated by default as identity,
    name varchar(255)

);
create table Event
(

    id     int primary key generated by default as identity ,
    file_id int,
    user_id int,
    foreign key (file_id)references file(id),
    foreign key (user_id)references users(id)

);